### ISSUE TITLE
 error: could not convert '{my_switch}' 

### ISSUE THREAD

**Issue by Monacoslo** [timmchugh11/Chinese-Diesel-Heater---ESPHome#3]
When trying to compile, I get this error
`Compiling .pioenvs/avtodom-heater/lib67b/ESP8266WiFi/ESP8266WiFiScan.cpp.o
/config/esphome/avtodom-heater.yaml: In lambda function:
/config/esphome/avtodom-heater.yaml:200:28: error: expected type-specifier before 'HeaterSwitch'
  200 |       auto my_switch = new HeaterSwitch(id(heater_serial));
      |                            ^~~~~~~~~~~~
/config/esphome/avtodom-heater.yaml:202:24: error: could not convert '{my_switch}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::switch_::Switch*>'
  202 |       return {my_switch};
      |                        ^
      |                        |
      |                        <brace-enclosed initializer list>
Compiling .pioenvs/avtodom-heater/lib67b/ESP8266WiFi/WiFiClient.cpp.o
*** [.pioenvs/avtodom-heater/src/main.cpp.o] Error 1`

What is wrong?

**Comment by timmchugh11** [comment]
I left the testing switch I was using to try and control the heater, but the related switch files isnt present, I have commited chages to fix the error

1d58639aab0a5a5ad278e88b7f163bec0dbcccda
